name: Build DLL on Pull Request

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Compile DLL
        shell: powershell
        run: |
          # Compile test.cpp to libTest.dll in CPPProj folder
          g++ -shared -o Collaboration\libTest.dll CPPProj\libraries\test.cpp

      - name: Commit and push DLL
        shell: powershell
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Collaboration\libTest.dll
          git commit -m "Auto-build DLL on PR"
          git push


